services:
  postgres:
    container_name: authPostgresDB
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5440:5432"